name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test-build:
    name: Lint, Test, & Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Configure git for private modules
        run: git config --global url."https://${{ github.token }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Setup tools
        run: make setup-tools

      - name: Generate code
        run: cd frontend && bun install && cd .. && make generate-all

      - name: Run migrations
        run: make migrate

      - name: Install Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}

      - name: Lint Proto
        run: buf lint proto

      - name: Check Breaking Changes
        if: github.event_name == 'pull_request'
        run: buf breaking proto --against "https://${{ github.token }}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git#branch=main"

      - name: Lint Go
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest

      - name: Run tests
        run: richgo test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
        env:
          RICHGO_FORCE_COLOR: 1

      - name: Build
        run: make build
